# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/toude/Documents/GitHub/Miaki

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/toude/Documents/GitHub/Miaki

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toude/Documents/GitHub/Miaki/CMakeFiles /home/toude/Documents/GitHub/Miaki//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toude/Documents/GitHub/Miaki/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build_kernel

# Build rule for target.
build_kernel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_kernel
.PHONY : build_kernel

# fast build rule for target.
build_kernel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_kernel.dir/build.make CMakeFiles/build_kernel.dir/build
.PHONY : build_kernel/fast

#=============================================================================
# Target rules for targets named build_deeper_spoofer

# Build rule for target.
build_deeper_spoofer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_deeper_spoofer
.PHONY : build_deeper_spoofer

# fast build rule for target.
build_deeper_spoofer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_deeper_spoofer.dir/build.make CMakeFiles/build_deeper_spoofer.dir/build
.PHONY : build_deeper_spoofer/fast

#=============================================================================
# Target rules for targets named build_user

# Build rule for target.
build_user: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_user
.PHONY : build_user

# fast build rule for target.
build_user/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_user.dir/build.make CMakeFiles/build_user.dir/build
.PHONY : build_user/fast

#=============================================================================
# Target rules for targets named build_devmode

# Build rule for target.
build_devmode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_devmode
.PHONY : build_devmode

# fast build rule for target.
build_devmode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_devmode.dir/build.make CMakeFiles/build_devmode.dir/build
.PHONY : build_devmode/fast

#=============================================================================
# Target rules for targets named build_qaf_qafull

# Build rule for target.
build_qaf_qafull: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_qaf_qafull
.PHONY : build_qaf_qafull

# fast build rule for target.
build_qaf_qafull/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_qaf_qafull.dir/build.make CMakeFiles/build_qaf_qafull.dir/build
.PHONY : build_qaf_qafull/fast

#=============================================================================
# Target rules for targets named build_qaf_sceshell

# Build rule for target.
build_qaf_sceshell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_qaf_sceshell
.PHONY : build_qaf_sceshell

# fast build rule for target.
build_qaf_sceshell/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_qaf_sceshell.dir/build.make CMakeFiles/build_qaf_sceshell.dir/build
.PHONY : build_qaf_sceshell/fast

#=============================================================================
# Target rules for targets named build_qaf_debugflag

# Build rule for target.
build_qaf_debugflag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_qaf_debugflag
.PHONY : build_qaf_debugflag

# fast build rule for target.
build_qaf_debugflag/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_qaf_debugflag.dir/build.make CMakeFiles/build_qaf_debugflag.dir/build
.PHONY : build_qaf_debugflag/fast

#=============================================================================
# Target rules for targets named build_yellowmsg

# Build rule for target.
build_yellowmsg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_yellowmsg
.PHONY : build_yellowmsg

# fast build rule for target.
build_yellowmsg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_yellowmsg.dir/build.make CMakeFiles/build_yellowmsg.dir/build
.PHONY : build_yellowmsg/fast

#=============================================================================
# Target rules for targets named build_lowact

# Build rule for target.
build_lowact: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_lowact
.PHONY : build_lowact

# fast build rule for target.
build_lowact/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_lowact.dir/build.make CMakeFiles/build_lowact.dir/build
.PHONY : build_lowact/fast

#=============================================================================
# Target rules for targets named build_kms

# Build rule for target.
build_kms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_kms
.PHONY : build_kms

# fast build rule for target.
build_kms/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_kms.dir/build.make CMakeFiles/build_kms.dir/build
.PHONY : build_kms/fast

#=============================================================================
# Target rules for targets named build_kmspico

# Build rule for target.
build_kmspico: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_kmspico
.PHONY : build_kmspico

# fast build rule for target.
build_kmspico/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_kmspico.dir/build.make CMakeFiles/build_kmspico.dir/build
.PHONY : build_kmspico/fast

#=============================================================================
# Target rules for targets named build_spoofer_tool

# Build rule for target.
build_spoofer_tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_spoofer_tool
.PHONY : build_spoofer_tool

# fast build rule for target.
build_spoofer_tool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_spoofer_tool.dir/build.make CMakeFiles/build_spoofer_tool.dir/build
.PHONY : build_spoofer_tool/fast

#=============================================================================
# Target rules for targets named build_spoofer_test

# Build rule for target.
build_spoofer_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_spoofer_test
.PHONY : build_spoofer_test

# fast build rule for target.
build_spoofer_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_spoofer_test.dir/build.make CMakeFiles/build_spoofer_test.dir/build
.PHONY : build_spoofer_test/fast

#=============================================================================
# Target rules for targets named build_spoofer_vita

# Build rule for target.
build_spoofer_vita: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_spoofer_vita
.PHONY : build_spoofer_vita

# fast build rule for target.
build_spoofer_vita/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_spoofer_vita.dir/build.make CMakeFiles/build_spoofer_vita.dir/build
.PHONY : build_spoofer_vita/fast

#=============================================================================
# Target rules for targets named build_all

# Build rule for target.
build_all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_all
.PHONY : build_all

# fast build rule for target.
build_all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_all.dir/build.make CMakeFiles/build_all.dir/build
.PHONY : build_all/fast

#=============================================================================
# Target rules for targets named move_plugins

# Build rule for target.
move_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 move_plugins
.PHONY : move_plugins

# fast build rule for target.
move_plugins/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/move_plugins.dir/build.make CMakeFiles/move_plugins.dir/build
.PHONY : move_plugins/fast

#=============================================================================
# Target rules for targets named build_miaki

# Build rule for target.
build_miaki: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_miaki
.PHONY : build_miaki

# fast build rule for target.
build_miaki/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_miaki.dir/build.make CMakeFiles/build_miaki.dir/build
.PHONY : build_miaki/fast

#=============================================================================
# Target rules for targets named ALL_TARGET

# Build rule for target.
ALL_TARGET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ALL_TARGET
.PHONY : ALL_TARGET

# fast build rule for target.
ALL_TARGET/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ALL_TARGET.dir/build.make CMakeFiles/ALL_TARGET.dir/build
.PHONY : ALL_TARGET/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ALL_TARGET"
	@echo "... build_all"
	@echo "... build_deeper_spoofer"
	@echo "... build_devmode"
	@echo "... build_kernel"
	@echo "... build_kms"
	@echo "... build_kmspico"
	@echo "... build_lowact"
	@echo "... build_miaki"
	@echo "... build_qaf_debugflag"
	@echo "... build_qaf_qafull"
	@echo "... build_qaf_sceshell"
	@echo "... build_spoofer_test"
	@echo "... build_spoofer_tool"
	@echo "... build_spoofer_vita"
	@echo "... build_user"
	@echo "... build_yellowmsg"
	@echo "... move_plugins"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

