name: Build Miaki

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make git wget cmake python-is-python3 bzip2

    - name: Install VitaSDK
      run: |
        git clone https://github.com/vitasdk/vdpm
        cd vdpm
        ./bootstrap-vitasdk.sh
        ./install-all.sh
        echo export VITASDK=/usr/local/vitasdk >> ~/.bashrc
        export PATH=$VITASDK/bin:$PATH >> ~/.bashrc

    - name: Build Miaki
      run: |
        make
