name: Build and Release Miaki

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make git wget cmake python-is-python3 bzip2
    
    - name: Setup environment variables
      run: |
        echo "VITASDK=/usr/local/vitasdk" >> $GITHUB_ENV
        echo "PATH=/usr/local/vitasdk/bin:$PATH" >> $GITHUB_ENV

    - name: Install VitaSDK
      run: |
        git clone https://github.com/vitasdk/vdpm
        cd vdpm
        ./bootstrap-vitasdk.sh
        sudo ./install-all.sh

    - name: Verify VitaSDK
      run: |
        vitacompiler --version
        echo "VITASDK=$VITASDK"
        echo "PATH=$PATH"
        
    - name: Build Miaki
      run: |
        make

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: true
        prerelease: false
        body: |
          Release brouillon pour Miaki ${{ github.ref_name }}.
          Fichier .vpk pour PlayStation Vita.
          Consultez le README pour les instructions d'installation.

    - name: Upload VPK to Release
      uses: actions/upload-release-asset@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./miaki.vpk
        asset_name: miaki-${{ github.ref_name }}.vpk
        asset_content_type: application/octet-stream
