name: Build and Release Miaki

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make git wget cmake python-is-python3 bzip2
    
    - name: Setup environment variables
      run: |
        echo "VITASDK=/usr/local/vitasdk" >> $GITHUB_ENV
        echo "PATH=/usr/local/vitasdk/bin:$PATH" >> $GITHUB_ENV

    - name: Install VitaSDK
      run: |
        git clone https://github.com/vitasdk/vdpm
        cd vdpm
        ./bootstrap-vitasdk.sh
        sudo ./install-all.sh

    - name: Verify VitaSDK
      run: |
        vitacompiler --version
        echo "VITASDK=$VITASDK"
        echo "PATH=$PATH"
        
    - name: Build Miaki
      run: |
        make

   