name: Build Miaki

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make git wget cmake python bzip2

    - name: Install VitaSDK
      run: |
        git clone https://github.com/vitasdk/vdpm
        cd vdpm
        ./bootstrap-vitasdk.sh

    - name: Setup VitaSDK
      run: | 
        ./install-all.sh
        echo "VITASDK=$HOME/vitasdk" >> $GITHUB_ENV
        echo "$HOME/vitasdk/bin" >> $GITHUB_PATH

    - name: Build Miaki
      run: |
        make
